#ifndef SUBTASK_H
#define SUBTASK_H

#include "task.h"
class subTask:public task
{
    task* mSuper;//pointer to the super task generated by
    u32 mIndex;  //index of the Ip list
  public:
    subTask(TASKTYPE type, u32 duration, u32 id, u32 index, task* pt = nullptr):task(type,duration,id)
    {
        mSuper = pt;
        mIndex = index;
    }
    void setSuper(task* sup){mSuper = sup;}
    bool exec() override;
    void notifyUpdate(u32 sig) override;

  protected:
     virtual bool execAtLocal(); 
     virtual bool execAtTelnet(); 
     virtual string combineCmd(bool blocal);
};

#endif // SUBTASK_H
